--- 
- hosts: 172.31.21.92 
  become: yes 
  tasks: 
  - include_tasks: myfile1.yml 
  - name: i want to install webserver on ansible node 
    apt: 
      name: apache2 
      state: present 
  - name: i want copy index file into ansible node side 
    templates: 
        src: myindex-j2
        dest: /var/www/html/index.html