--- 
- name: create a new tomcat group 
  group: 
    name: tomcat 
    state: present 
- name: create a new tomcat_user 
  user:
    name: tomcat
    shell: /bin/false
    groups: tomcat 
    home: /opt/tomcat 
    state: present 

  